### PR TITLE
Labels

### PR DESCRIPTION
**Pull request by vktr**
Add label support to PicoTorrent. This has been requested over the years and I think it's a really good idea and we can make it really awesome 😸

Opening this as early as possible to gather feedback.

Features
- [x] Label colors
- [x] Per-label save path
- [x] Filter the list view on labels
- [x] Apply label in 'Add torrent' dialog
- [x] Persist torrent labels

I'd like feedback on features from @birkoffe @mutt3x @disfated @Yinchie @GATOQSECOMIO @smaragdus @PixelEater. I've seen you either reporting this as a missing feature, or liking an issue reporting this as a missing feature. Feel free to un-watch if you're not interested, and sorry for mentioning you if so 😄 

I want to do this right, which is why I'm involving you early.

Screenshots of the editing page

image

### CODE REVIEW

**Comment by mutt3x** [comment]
MSP FTW Visual Concept as i see it.
The color represents the label it is in.
hUeaVEN

This is highly effective when you have many torrents from many (private) trackers. By far easy to see where the torrent is from. This idea can be manipulated even further by adding custom icons.

But something is missing and i dont now what. Perhaps it is the side panel from uT that has all the labels listed. In Pico this can be done from the filter list.

Also dont forget the option of automation + labels. The label that once you put it on a torrent automatically  gets its premade destination (very well made in rtorrent). This can also be build upon by adding premade speeds.

Lets not forget this also opens up a whole new dimension to torrent ordering, just imagine the form where you can order all torrents alphabetically by label. Amazing stuff for someone who gets where im going with this.

The more possibilities you add to the labels the better, trust me magic will happen.
Furthermore, i guess the goal is to optimize Pico for high torrent seed count and make it confront web and seedbox use.

Either way, the fact that this is being worked on is a huge leap.
Keep it clean, keep it minimal. Shine in glory for all men to see.

**Comment by vktr** [comment]
Here's some screenshots,

The torrent list view with two different labels each with their own color;
image

Label submenu in the torrent context menu;
image

Label filtering menu (yes, you can apply both a regular filter *and* a label filter);
image

**Comment by mutt3x** [comment]
ohh yes.

It would be also good to add a label column in case people want to see the name of the label. In a way that column could also somehow either show the label name in text or rather its custom icon.



Curiosity:
See how the trackers on the left panel are showing icons. Kinda not label related but a list on its own. Im not sure if that is user-made or the client grabs it by itself. Ive seen users on private trackers grab the site favicon and use it as a label icon...

**Comment by TechnoGreg** [comment]
I'm maybe not expected to give my opinion, but if I had to :
- Labels will be materialized by a new column displaying the label name (can show/hide the column like the other ones, and it will disabled labels is hidden)
- I will hope to choose color from a preconfigurd list or via a color palette
- And maybe a little dot of the concerned color just before the label name, wherever you put the label menu

**Comment by vktr** [comment]
@mutt3x Yeah, a label column is coming. There will also be the option of having either the row background filled or an icon in the label column. That's a pretty cool idea with the icons, but I think we'll stick to a single color for the first iteration.

@TechnoGreg Everyone is welcome 😃 I want as much ideas as possible since the earlier we know about them, the easier it would be to implement them.

- The Label column will be added as mentioned, however I don't think it's intuitive to disable labels if you hide the column. If you have no labels, or set the label filter to None, it's the same as disabling labels.
- As of now, it's a free text input for a hex color, but a color palette is a good idea. There is one in wxWidgets we can use.
- How we can show the color depends on the context. Since the menus are radio items as well, I don't think it can show both an icon and a radio check item, I'll check!
- I have a few ideas on activation triggers for labels, perhaps starting with regular expressions or something to automatically suggest a label when you add a torrent.

**Comment by TechnoGreg** [comment]
@vktr I can understand your reasoning concerning the first point
And I'm watching forward to this triggers, will be nice

Ho I'm thinking about something, you wrote about per-label save path, maybe we can imagine per-label sped limit, or priority setting ?

**Comment by vktr** [comment]
Yeah, we can add per-label whatever-we-want, the "issue" is that for speed limit or priority etc, we need a way to adjust them per torrent in the UI, in case you want to change the settings after the label has applied the settings 😃 

I'm starting with save paths for this PR, then we can add another PR where we add a torrent properties dialog where one can change (for example) speed limits, connection limits, etc. And then we can add label support to that.

**Comment by mutt3x** [comment]
Imagine each label you make can show you how much you have uploaded and downloaded since... well ever, like the stats you have in a single torrent but this is for the whole label. Calculate the ratio of the label.
I imagine this could also be costly on memory but what do i know how a software works. just an idea, might be interesting to someone. This can also be made as an option within the label itself just like the color.  Also, since on private trackers the tracker is always the same this can be done with the tracker option as well.

I mean its insane what you can do with this and its a joy really. You need to ask the people in the center of it all and you can get some insane ideas.

All you need is the 'allow the user to be a power user' mentality.

**Comment by vktr** [comment]
Those are pretty neat ideas @mutt3x! It ties in quite well with what I have on the roadmap - some sort of statistics overview, etc.

**Comment by birkoffe** [comment]
* may be add separate column labels and apply color only for it ? too colorful now.
* possibility add more then one label per torrent (in my common usage `series` and `to-do`)

**Comment by vktr** [comment]
Hey @birkoffe! I'm working on adding a choice to either have the list item background or a label set. I think we mentioned it above.. Also, I'm planning on adding tags in the future, and I think the use-case is that a torrent can have zero or one label, and zero or many tags.

**Comment by mutt3x** [comment]
Generally you can only play with one color in line. when you see one color you know what it is but once you place more colors its a mess. Icons on the other hand... but i think the way things are shaping now is good, so good Pico will become a client with unique label features on the 'market', if not the best i dare to say.

Regarding giving torrents several labels/tags... idk how is that going to work really or whats the end game here. Im always trying to place myself in the shoes of the idea but i just dont see it useful. You could possibly tag things as pictures, video, audio but for what use, you already know what it is.
The known term cross-seeding could potentially be used for such matter but then again you can make an option in the torrent itself to ''call it'' cross-seeding.

On a side note, one more thing: make hotkeys for each label. One unique hotkey to show all torrents lets say shift+A and the rest are custom per label. So if you want to only show the ISO label you press shift+X for an example. i wont say its faster but it could be more convenient for some people.

**Comment by vktr** [comment]
I think the main idea I had for tags was automatic tagging of torrents - ie movies would automatically get tagged with 1080p/BluRay etc which would make it easier and more performant to write cool filtering queries later when we add that.

**Comment by mutt3x** [comment]
ahh i see, very nice idea. i usually have 1080/BR but... that does not mean its useless, you could also make it grab intel from the name and guess whats in the name... the scene/P2P group name. thats an interesting filter for you to think about in the future.
secrets secrets.

**Comment by vktr** [comment]
image

There is now the option to either have a row background color or (as the image shows) a column with the label.

**Pull request merged**
