### PR TITLE
Added translations for PR #892

### PR DESCRIPTION
**Pull request by TechAdvancedCyborg**
Added translations for PR #892

### CODE REVIEW

**Comment by vktr** [comment]
Thanks, awesome work. I'll put this on hold until the PR is actually complete - there might be new strings incoming.

**Comment by TechAdvancedCyborg** [comment]
Yup also in both languages files, is it me, or is the "leeches" string unused?

**Comment by vktr** [comment]
There are a few unused translations, there's a PR incoming to remove all unused translations in all languages along with some PowerShell scripts to help maintain translations.

**Comment by TechAdvancedCyborg** [comment]
Nice!

**Comment by TechAdvancedCyborg** [comment]
Fixing a bunch of stuff that sound better considering the context.

**Pull request merged**
