### PR TITLE
Add Breakpad for release builds

### PR DESCRIPTION
**Pull request by vktr**
This will add Google Breakpad for our release builds. If a crash occurs, the user will be asked to send an (anonymous) error report. The error report contains the version, branch, commitish and a minidump. The reports are sent to https://api.picotorrent.org/minidump.

Breakpad is added in a quite unusual way - I've moved the relevant source files to our source tree, under `src/breakpad`. One of the major reasons for this is the rather complex way of building and distributing Breakpad.

### CODE REVIEW

**Comment by AFaustini** [comment]
The unhandled exception continue when i tried to add the majority of my torrents files. And the breakpad question doesn`t show up.

**Comment by vktr** [comment]
Sorry about the crashes, but thanks for your patience.

Which MSVC version do you have installed?

**Comment by AFaustini** [comment]
My 2017 MSVC is 14.13.26020, 2015 is 12.0.40664

**Comment by vktr** [comment]
Just tried on a clean Windows 10 (x64) machine. PicoTorrent installed correctly and would add and download a torrent without issue.

I also tried installing the redistributable separately and then running the portable version of PicoTorrent with no issues.

Although this was with the latest stable runtime release (14.12). It seems as if MSVC 14.13.26020 is a pre-release version of the runtime?

**Comment by AFaustini** [comment]
I am running the portable version. I uninstalled my version of runtime, and installed the 14.12 release, and the error occurs anyway.

**Comment by vktr** [comment]
Can you attach or send me a torrent file which gives you the error? viktor@viktorelofsson.se.

**Comment by vktr** [comment]
@AFaustini Thanks for your patience! I found the bug and have pushed a fix. Could you try the build here when it finished? https://ci.appveyor.com/project/picotorrent/picotorrent/build/624/job/6iq5cto4mxwy5e0d

**Comment by AFaustini** [comment]
Now it`s working flawless

**Pull request merged**
