### PR TITLE
Create an optional portable bundle zip package

### PR DESCRIPTION
**Pull request by zp**
Revisiting #165 due to demand.

Creates an optional zip file users can download that contains all the required runtime files, including `api-ms-win-*.dll` files for Windows versions prior to 10, so they can get a "true portable" PicoTorrent if they so desire.

~~I've kept it seperate from the base portable package, to follow the recent symbols package change. So users will need to download the base portable zip, and then this new runtime zip and extract the files to where they put `PicoTorrent.exe`~~

### CODE REVIEW

**Comment by vktr** [comment]
I wouldn't mind including the PicoTorrent binaries (.exe and .dll) in the portable zip package. It would make it easier in download-and-extract scenarios.

**Comment by zp** [comment]
So have 2 portable zips, a basic 'non installer' version (the current .zip) , and then a 'fully portable' version? (i'll change .runtime to .portable, like you initially suggested)

**Comment by vktr** [comment]
Yes, or do you think it would be confusing?

**Comment by zp** [comment]
I don't think it's confusing, you could also direct users as to which package they'll probably want in the release notes.

**Pull request merged**
