### PR TITLE
Fix some french mistakes

### PR DESCRIPTION
**Pull request by Gladorme**
"Cryptage" doesn't exist in french. And Ko/s is really different from Kb/s !

### CODE REVIEW

**Comment by Gladorme** [comment]
Strange, the limit is expressed in Kb/s but in the main interface it is in Ko/s .-.

**Comment by TechnoGreg** [comment]
Ko/s = KB/s
Tant qu'à parler français, pour pas octet plutôt que Byte ?

**Comment by Gladorme** [comment]
My bad, sorry. I didn't think that was different  :[

**Comment by vktr** [comment]
Let me know when this is read to merge! 😄

**Comment by TechnoGreg** [comment]
I think the rest is absolutely ok

**Comment by Gladorme** [comment]
I think it is good 👍

**Pull request merged**
