### PR TITLE
Better installer

### PR DESCRIPTION
**Pull request by vktr**
Build a better installer. The default one in WiX does not handle high DPI displays - this one does. It also looks spicier.

- [x] Installer can install
- [x] Installer can uninstall
- [x] Installer can upgrade
- [x] If installer fails, show link to GitHub issues and also have link to log file

image

### CODE REVIEW

**Comment by TechAdvancedCyborg** [comment]
this looks 🌶️

**Comment by Nychobon** [comment]
A reasonable suggestion might be to add (kind of like qBittorrent's function in its installer) an exception to the Windows Firewall when installing so it doesn't annoy you on the first load of the application.
I'm not sure if this should be an option or whether to make it necessary, though (given Windows Firewall might be disabled).

On a side note, file extension/magnet URI association in the installer like most applications generally ask you about before trying to set them too. Might need to make a dropdown-type menu (think, the installer for Maxthon browser for instance which has it at the bottom) for these options to save space unless expanded.

Big props and appreciation to taking non-default DPI settings into consideration too. I'm glad someone actually cares about it. (Btw, rocking PicoTorrent on Vista x64 and it works perfectly, don't judge for my OS lol)

**Comment by vktr** [comment]
@Nychobon Those are great suggestions! I think we can fit the Windows Firewall and file extension/magnet URI associations between the install location and the checkbox for dependencies, or at least have a "Show more" button to display them.

**Comment by Nychobon** [comment]
>or at least have a "Show more" button to display them.

Yeah, this is probably better as a whole and kinda what I was hinting at in the first place with the description of an installer that does a similar thing. Thanks for the thumbs up, glad I could actually be of help/advice!

I think PicoTorrent is the only currently-updated x64 BT client that still works fine on the aged Vista without any kernel extensions, whether this was intentional or not, it's a nice surprise.

**Comment by vktr** [comment]
> I think PicoTorrent is the only currently-updated x64 BT client that still works fine on the aged Vista without any kernel extensions, whether this was intentional or not, it's a nice surprise.

It is not intentional - I actually haven't done any testing on anything lower than Windows 7 😅 I'm happy you like it and pretty gool that it works on Vista!

**Pull request merged**
