### PR TITLE
Add required runtime files to portable package.

### PR DESCRIPTION
**Pull request by zp**
Copies to required runtime DLLs to the publish directory to be zipped up for the portable packages.

Should be the solution #153 is looking for.

### CODE REVIEW

**Comment by vktr** [comment]
Did you test this on a machine without the runtime? I had the same idea as you but there's a few more files needed, `api-ms-win-crt-runtime-l1-1-0.dll` among others, and that's when I dropped the ball :smile:

**Comment by zp** [comment]
I created a new Windows 10 virtual machine and it loaded fine with just the 2 DLLs.

I will create a Windows 7 virtual machine and test it as well.

**Comment by vktr** [comment]
That's great, I only tried on a W7 machine. If you get it working on W7 you can merge this.

**Comment by zp** [comment]
Probably going to close this as a 'wontfix', it appears that the Universal CRT is included in Windows 10, which is why it only needs the 2 C++15 runtime DLLs.

Windows 7/8/8.1 require 20 different `api-ms-win-*.dll` files, so it's probably best to just ask users to install the C++ redist for their desired PicoTorrent platform.

**Pull request closed without merging**
