### PR TITLE
Russian language

### PR DESCRIPTION
**Pull request by AnonimusRus**
I have already done some translation work. But at first we need testing of work this translation, lol.

### CODE REVIEW

**Comment by vktr** [comment]
Great work! To test it, you can download the PicoTorrent portable and put your language JSON in the `langs` directory, then start PicoTorrent. You should be able to select your language from the dropdown in Preferences.

**Comment by AnonimusRus** [comment]
I have got a problem. How can I download my "1049.json" file?

**Comment by vktr** [comment]
It should be on your computer, or how else did you push it to GitHub? Or did you use the web interface functions? If so, it's right here, https://raw.githubusercontent.com/AnonimusRus/picotorrent/patch-1/lang/1049.json

**Comment by AnonimusRus** [comment]
Wow! My translation is work! 
But I see some troubles. Some letters get out of visible part of lines..

**Comment by vktr** [comment]
Nice! For those translations, could you make them shorter?

**Comment by AnonimusRus** [comment]
Ok, I'm done for now (almost).

**Comment by vktr** [comment]
Let me know when you're finished and I'll merge it :smile:

**Comment by AnonimusRus** [comment]
You can merge this version of translating. Basically, most of the text was translated.

**Comment by AnonimusRus** [comment]
Build of 3 Updates was cancelled. Did you get into troubles?

**Comment by vktr** [comment]
No trouble, just not worth the build since its only a JSON file :smile:

**Pull request merged**
