### PR TITLE
Fix a bug in how we store list view column state

### LINKED ISSUE #443: UI.dat continues to behave weirdly, even after the update
So, it doesn't matter how I arrange the column tab, whenever I close and open the client not only the tabs are not saved but sometimes they are completely scrambled.

Here's a video to help understand

https://gfycat.com/RaggedShoddyAlligatorsnappingturtle

At this point I would've just given up but this is by far the best torrent client there is

### PR DESCRIPTION
**Pull request by vktr**
@fidelc when the AppVeyor build is finished, could you verify the fix?

Closes #443

### CODE REVIEW

**Comment by vktr** [comment]
https://ci.appveyor.com/project/picotorrent/picotorrent/build/547/job/rt2hmhwtxmvylch4/artifacts

Here's the x64 artifacts. You can use the portable (.zip) version if you don't wish to uninstall you existing version to try.

**Comment by fidelc** [comment]
Everything seems to be working fine now expect the order. 
I select it to show the newer torrents first  but it gets reseted after closing it

**Comment by vktr** [comment]
Yes, the sort state is not saved. This only addresses the column order. I'll put in another PR for storing the sort state.

**Comment by fidelc** [comment]
Thank you for that

**Pull request merged**
