### PR TITLE
Catalan language

### PR DESCRIPTION
**Pull request by enr00ted**

### CODE REVIEW

**Comment by vktr** [comment]
Looks good :smile: If you change the `lang_name` to english we are good to go!

**Comment by vktr** [comment]
@enr00ted Would you mind the mentioned change? Otherwise I'll merge it and fix it myself :smile:

**Comment by enr00ted** [comment]
Sorry been really busy. Is it done already ? :)

**Comment by vktr** [comment]
Thanks! :smile:

**Pull request merged**
