### PR TITLE
Switch to wxWidgets

### PR DESCRIPTION
**Pull request by vktr**
This pull request will move PicoTorrent from the raw Windows APIs to wxWidgets for GUI work.

PicoTorrent has always relied on being lightweight, but the amount of work necessary to bring standard features into PicoTorrent (such as a tree list view) is alot, so this will ease things up a bit by using wxWidgets where such controls already exists.

The decision to use wxWidgets is based on what I value in PicoTorrent - native look and feel, responsive UI, low memory usage and high performance. wxWidgets builds on top of the native APIs available on that platform, meaning it will look native across platforms. **Yes, that's right, PicoTorrent will become cross platform!**

Let me know your thoughts about this!

### CODE REVIEW

**Comment by AFaustini** [comment]
Would be cool if we had access to alpha builds as they shown in the picotorrent gitter, like this: https://ci.appveyor.com/project/picotorrent/picotorrent/build/614
I can download but the app cant open due a mismatch error between the program and library build versions.

**Comment by vktr** [comment]
@AFaustini I'm sorry the AppVeyor builds aren't working - I'll see what I can do! They need to work before merging at least. Thanks for pointing this out 😄

**Comment by vktr** [comment]
@AFaustini The latest builds should work fine for preview and testing the PR 😄

**Comment by AFaustini** [comment]
Thx, the new build is working well.

**Comment by vktr** [comment]
Great! Let me know if you have any questions or run into any issues.

**Comment by AFaustini** [comment]
You can count me in. The DHT bug of stable version has been fixed.

**Comment by vktr** [comment]
What type of torrents? Can you tell me the steps to reproduce it?

**Comment by AFaustini** [comment]
It's random. Sometimes i click in a random torrent, and the app crash.

**Comment by vktr** [comment]
Odd - I'll see if I can come up with a reproduce and a fix :)

**Comment by AFaustini** [comment]
When i try to add torrents, the program quits itself with a unhandled exception.

**Comment by vktr** [comment]
Which version of Windows are you running? Could you try with a different
torrent file?

**Comment by AFaustini** [comment]
Windows 10.
I tried with a lot of torrent files.

**Comment by vktr** [comment]
Do you use the add torrent dialog or do you double click them to add from
explorer?

**Comment by AFaustini** [comment]
Add torrent dialog. I use picotorrent in a portable way.

**Comment by AFaustini** [comment]
Now there isn`t any option to force downloads, (force downloading more torrents than the queue is set/allowed to do). This behavior is by design or it`s a bug?

**Comment by dertuxmalwieder** [comment]
How does the wxWidgets switch affect performance? One of the major reasons why I adore PicoTorrent is its superb starting time.

**Comment by vktr** [comment]
@dertuxmalwieder The executable file size has increased a bit, but the startup speed and general memory usage and performance should still be the same!

**Pull request merged**
