### PR TITLE
Total rework of french translations.

### PR DESCRIPTION
**Pull request by TechAdvancedCyborg**
Took a bit of work, but here is it, a total rework of french translations.

### CODE REVIEW

**Comment by vktr** [comment]
Awesome stuff! I really appreciate the effort!

**Comment by TechAdvancedCyborg** [comment]
x86 artifact build didn't update languages?

**Comment by TechAdvancedCyborg** [comment]
Oh well, gonna go to sleep...

**Comment by vktr** [comment]
I'll have a look and see. Thanks!

**Pull request merged**
