### PR TITLE
v0.19 release preparations

### PR DESCRIPTION
**Pull request by vktr**
This became a huge rewrite with a move to wxWidgets (among other things).

### CODE REVIEW

**Comment by TechAdvancedCyborg** [comment]
Soon™

**Comment by vktr** [comment]
If you're eager the preview binaries are on AppVeyor. There's a few things missing but mostly it'll work as it should :)

**Comment by TechAdvancedCyborg** [comment]
Yay

**Comment by TechAdvancedCyborg** [comment]
And it works 👍

**Comment by TechAdvancedCyborg** [comment]
Screenshot (43)

**Comment by TechAdvancedCyborg** [comment]
Using [latest build](https://ci.appveyor.com/project/picotorrent/picotorrent/builds/33415853) magnet links don't open a dialog for adding torrent...

**Comment by vktr** [comment]
@TechAdvancedCyborg I haven't had time to implement that 100% yet, all pieces are there but the final things are missing. Thanks for bringing it to my attention!

**Comment by TechAdvancedCyborg** [comment]
Np, thank you so much for taking the time to make this piece of software!

**Comment by vurghus-minar** [comment]
@vktr Truly amazing job! Thank you!

### Issue:
Tray Icon context menu 'exit' not functional 
 
Running latest 0.19 portable build on Windows 10 version 1909.

### Steps to reproduce
When clicking exit in notification area icon context menu, the app does not exit.
Preferences set to minimizing and closing to tray although changing these to default does not solve the issue.

**Comment by TechAdvancedCyborg** [comment]
Context menu doesn't even show up for me... :(

**Comment by vktr** [comment]
@vurghus-minar thanks for reporting! I'll fix it.

@TechAdvancedCyborg are you right clicking the tray icon?

**Comment by TechAdvancedCyborg** [comment]
It didn't work at first then it did...

**Comment by vktr** [comment]
Odd - let me know if you figure out how to reproduce it 🤔 Yeah, I'll fix exit. Thanks for testing!!

**Comment by TechAdvancedCyborg** [comment]
Yup

**Comment by kaecy** [comment]
wxWidgets again. The phoenix rises again.

**Comment by vktr** [comment]
@TechAdvancedCyborg when PicoTorrent crashes, do you get the dialog telling you it crashed?

**Comment by TechAdvancedCyborg** [comment]
Nope

**Comment by TechAdvancedCyborg** [comment]
Nothing just crashes

**Comment by vktr** [comment]
Thanks, I'll look into it

**Comment by TechAdvancedCyborg** [comment]
Also, I am not on the latest build because Appveyor can't find packages on build.

**Comment by TechAdvancedCyborg** [comment]
```Restoring NuGet package Cake.0.33.0.
Restoring NuGet package WiX.3.11.1.
WARNING: Unable to find version '0.33.0' of package 'Cake'.
WARNING: Unable to find version '3.11.1' of package 'WiX'.
Could not find Cake.exe
At C:\projects\picotorrent\build.ps1:51 char:5
+     Throw "Could not find Cake.exe"
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not find Cake.exe:String) [], RuntimeException
    + FullyQualifiedErrorId : Could not find Cake.exe
 
Command exited with code 1```

**Comment by TechAdvancedCyborg** [comment]
Thank you!

**Comment by vktr** [comment]
Dunno why AppVeyor couldn't find Cake, probably an intermittent error. Anyways, I can reproduce the issue so I'll make sure to push a fix for it.

**Comment by vktr** [comment]
@TechAdvancedCyborg The builds are working again :)

**Comment by TechAdvancedCyborg** [comment]
Yup I saw, thanks! 👍

**Comment by TechAdvancedCyborg** [comment]
v0.19 is out!

**Comment by vktr** [comment]
@TechAdvancedCyborg Almost :) There's a few more preparations, but quite soon!

**Pull request merged**
